### ISSUE TITLE
Naprawcie ten listener.

### ISSUE THREAD

**Issue by PolskiStevek** [PolskiStevek/Blaze-PvP#3]
Naprawienie tego klikania. InventoryClickEvent. Kod który powinien działać jest zawarty w core, i nie sprawia problemów. Wina leży po stronie innej klasy lub jakiegoś konfliktu. Po wyłączeniu core klikanie działa normalnie. Polecam spróbować wyłączyć rejestrowanie klasy InventoryClickListener w Blaze.java i sprawdzić czy problem występuje na światach innych niż "world".

_Wysłano z mojego K5 za pomocą [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Redo11** [comment]
Oczywiście, że działa wszędzie ty idioto.

**Comment by PolskiStevek** [comment]
no wiem dlatego to naprawcie

**Comment by Redo11** [comment]
Po prostu usune wszystkie klasy

**Comment by PolskiStevek** [comment]
skompiluj bez klasy InventoryClickListener i przetestuj na localhoscie

**Comment by Redo11** [comment]
To kurna zkompiluj mi najnowszego craft bukkita 1.8(narzędzia kompilują 1.13)

**Comment by PolskiStevek** [comment]
masz w foldere libraries, zreszta na 1.13 nie zadziała tylko actionbar

**Comment by Redo11** [comment]
Kurwa masz racje

**Comment by PolskiStevek** [comment]
xD
